name: CI

on:
  push:
    branches:
      - main

jobs:
  build_main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
    steps:
      - name: setup_python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: checkout_code
        uses: actions/checkout@v3
      - name: install_requirements
        run: |
          pip install numpy
